# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - DB=MYSQL CORE_RELEASE=master

before_script:
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - printf "\n" >> .env
  - echo 'YUBIAUTH_CLIENTID="12345"' >> .env
  - echo 'YUBIAUTH_APIKEY="t2ZMtKeValdA+H0jVpj3LIichn4="' >> .env
  - cp ./yubiauth/_config/config.yml.example ./yubiauth/_config/config.yml

script:
  - vendor/bin/phpunit yubiauth/tests  --coverage-clover=coverage.xml

after_success:
  - cd ~/builds/ss/yubiauth
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml