---
Name: yubiauthsecurity
After:
  - '#MFAAuthenticator'
---
Firesphere\YubiAuth\Forms\YubikeyLoginForm:
  authenticator_class: Firesphere\YubiAuth\Authenticators\YubikeyMemberAuthenticator
Firesphere\YubiAuth\Authenticators\YubikeyMemberAuthenticator:
  provider: %$Firesphere\YubiAuth\Providers\YubikeyAuthProvider